### ISSUE TITLE
Test suite failures when running pytest

### ISSUE THREAD

**Issue by badshah400** [Mathics3/mathics-core#1346]
## Description

Trying to build Mathics 8.0.0 for openSUSE Tumbleweed and running into many (~170) failing tests when running the test-suite using pytest. Full build log attached for failing build.

## How to Reproduce

1. Build Mathics3 8.0.0.
2. Run `pytest` from inside the `test` dir.
3. Error with pytest summary: 175 failed, 2738 passed, 287 skipped, 61 deselected, 14 xfailed, 16 xpassed, 3 warnings

## Output Given

As shown in this [build log](https://github.com/user-attachments/files/18631611/mathics-build.log).

## Expected behavior

Test suite should pass.

## Your Environment

OS: openSUSE Tumbleweed (Linux kernel 6.13.0, x86_64)

* GCC 14
* NumPy 1.26.4
* Pillow 11.1
* Python 3.11 and 3.12 (tested on both)
* Pytest 8.3.4
* SymPy 1.13.3
* SciPy 1.14.1
* scikit-image 0.25.0

## Workarounds

Skipping a whole bunch of failing tests individually using pytest label filtering.

## Additional context

Build tests are part of building Mathics RPM packages for openSUSE. Here is the specfile:

```spec
%if "%{flavor}" == "test"
%bcond_without test
%define psuffix -test
%else
%bcond_with test
%define psuffix %{nil}
%endif

# https://github.com/Mathics3/mathics-core/issues/932
%define skip_python313 1
%define pyname Mathics3
Name:           python-Mathics%{psuffix}
Version:        8.0.0
Release:        0
Summary:        A general-purpose computer algebra system
# Mathics itself is licensed as GPL-3.0 but it includes third-party software with MIT, BSD-3-Clause, and Apache-2.0 Licensing; also includes data from wikipedia licensed under CC-BY-SA-3.0 and GFDL-1.3
License:        Apache-2.0 AND BSD-3-Clause AND GPL-3.0-only AND MIT
URL:            https://mathics.github.io/
Source0:        https://github.com/Mathics3/mathics-core/releases/download/%{version}/%{pyname}-%{version}.tar.gz
BuildRequires:  %{python_module colorama}
BuildRequires:  %{python_module devel}
BuildRequires:  %{python_module mpmath >= 0.19}
BuildRequires:  %{python_module numpy < 2}
BuildRequires:  %{python_module pexpect}
BuildRequires:  %{python_module python-dateutil}
BuildRequires:  %{python_module setuptools}
BuildRequires:  %{python_module sympy >= 1.10.1}
BuildRequires:  fdupes
BuildRequires:  python-rpm-macros
Requires:       python-Mathics-Scanner >= 1.4.1
Requires:       python-Pint
Requires:       python-Pympler
Requires:       python-llvmlite
Requires:       python-mpmath >= 0.19
Requires:       python-numpy < 2
Requires:       python-palettable
Requires:       python-python-dateutil
Requires:       python-requests
Requires:       python-scipy
Requires:       python-sympy >= 1.10.1
Requires:       (python-Pillow >= 9.2 if python-base >= 3.7)
Requires(post): update-alternatives
Requires(postun): update-alternatives
Recommends:     python-scikit-image >= 0.17
BuildArch:      noarch
%if %{with test}
# SECTION For tests
BuildRequires:  %{python_module Mathics}
BuildRequires:  %{python_module Mathics-Scanner >= 1.4.1}
BuildRequires:  %{python_module Pillow >= 9.2 if %python-base >= 3.7}
BuildRequires:  %{python_module Pint}
BuildRequires:  %{python_module chardet}
BuildRequires:  %{python_module llvmlite}
BuildRequires:  %{python_module palettable}
BuildRequires:  %{python_module pytest}
BuildRequires:  %{python_module requests}
BuildRequires:  %{python_module scikit-image >= 0.17}
BuildRequires:  %{python_module stopit}
BuildRequires:  %{python_module testsuite}
BuildRequires:  %{python_module typing-extensions}
# /SECTION
%endif
Provides:       python-Mathics3 = %{version}
%python_subpackages

%description
Mathics is a general-purpose computer algebra system (CAS). It is meant to be a
free, lightweight alternative to Mathematica.

%prep
%autosetup -p1 -n mathics3-%{version}

# REMOVE SHEBANGS FROM FILES INSTALLED TO NON-EXEC LOCATIONS
pushd mathics
for d in `find ./ -prune -type d`
do
  find ${d} -name "*.py" -exec sed -i "1,4{/\/usr\/bin\/env/d}" '{}' \;
done
popd

%build
%if %{without test}
export USE_CYTHON=0
%python_build
%endif

%install
%if %{without test}
export USE_CYTHON=0
%python_install
%python_clone -a %{buildroot}%{_bindir}/mathics
%python_expand %fdupes %{buildroot}%{$python_sitelib}
%endif

%if %{with test}
%check
# Home page tests require django server up and running, test_gudermannian needs network access
# test_image: https://github.com/Mathics3/mathics-core/issues/837
pushd test
export USE_CYTHON=0
%pytest -k 'not (test_home_page or test_gudermannian or test_image)'
popd
%endif

%if %{without test}
%post
%python_install_alternative mathics

%postun
%python_uninstall_alternative mathics

%files %{python_files}
%license COPYING.txt
%doc README.rst AUTHORS.txt
%python_alternative %{_bindir}/mathics
%{python_sitelib}/mathics/
%{python_sitelib}/%{pyname}-%{version}-py%{python_version}.egg-info/
%endif

%changelog
```

**Comment by rocky** [comment]
Thanks for the report. 

It might have something to do with the build tree and the source tree being in different places. 

Some JSON tables must be created and used in the Mathics3 kernel. This may be causing the failure, although I don't see how the error message is exactly related to this.  

With the information you've given, I'll see if I can reproduce the failure and see what can be done to fix.

Is there a mode where one can build in the source tree? Or make sure that `mathics/data/operator-tables.json` and `mathics/data/op-tables.json` appear in both the source and build trees?

**Comment by rocky** [comment]
Also, thanks for packaging on OpenSUSE.

**Comment by badshah400** [comment]
Happy to help in whatever small way I can.

I tried to copy the test suite — the two json files in their appropriate location were already there — to inside the build tree and run the tests from there using `pytest`, but I run into the same issues. Will investigate this further and see if I am setting up the build dir correctly.

Thanks for your very useful app.

**Comment by rocky** [comment]
@badshah400 I am trying to reproduce the failures you see. You copied contents of `mathics.spec`  but what command is used that goes with that console log? (I tried `rpmbuild -ba mathics.spec` and get something very different. 

The tarball you used is from  https://github.com/Mathics3/mathics-core/releases/download/8.0.0/mathics3-8.0.0.tar.gz ? 

Also, it would be useful to have both the rpms for both Mathics-Scanner and the (buggy) Mathics3.  Thanks.

**Comment by mmatera** [comment]
Could be possible that the reason of the failing tests is that  `MATHICS_CHARACTER_ENCODING="ASCII"` was not set before running the tests?

**Comment by badshah400** [comment]
> [@badshah400](https://github.com/badshah400) I am trying to reproduce the failures you see. You copied contents of `mathics.spec` but what command is used that goes with that console log? (I tried `rpmbuild -ba mathics.spec` and get something very different.
>

On openSUSE, I use `osc build openSUSE_Tumbleweed x86_64`, but it requires having an [obs](https://build.opensuse.org/) account first.
 
> The tarball you used is from https://github.com/Mathics3/mathics-core/releases/download/8.0.0/mathics3-8.0.0.tar.gz ?
> 

```
Source0:        https://github.com/Mathics3/mathics-core/releases/download/%{version}/%{pyname}-%{version}.tar.gz
```

which resolves to `https://github.com/Mathics3/mathics-core/releases/download/8.0.0/Mathics3-8.0.0.tar.gz` (note capital `M` instead of small `m` in the tarball name). Using diff, it looks like they are the same tarball, so no problems there.

> Also, it would be useful to have both the rpms for both Mathics-Scanner and the (buggy) Mathics3. Thanks.

These are available from here:
https://download.opensuse.org/repositories/home:/badshah400:/branches:/science/openSUSE_Tumbleweed/noarch/

Just type in mathics in the search field at the top-right of the list. Sorry for the bit of a convoluted way to get these, and I would have loved to provide you direct links to the RPM themselves, but the build numbers change as I work on them rebuild them over and over, meaning such direct links would quickly expire.

**Comment by badshah400** [comment]
> Could be possible that the reason of the failing tests is that `MATHICS_CHARACTER_ENCODING="ASCII"` was not set before running the tests?
> 
> For testing, we compare always against the ASCII output.

Big thanks, this helped a lot. It whittled down the number of failures to 24 now (from 175 or so previously). So here is an updated log when running checks with the var  `MATHICS_CHARACTER_ENCODING="ASCII"` exported.

Here is the summary report from pytest. I also attach the updated build log in full, but I have not yet had a chance to examine these remaining issues in any detail — just wanted to quickly pass on my thanks for the help.

```
[  167s] =========================== short test summary info ============================
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Integers], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, False, False, Element[a, Integers], False, False, False}-Integers]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Primes], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{False, True, False, False, False, Element[a, Primes], False, False, False}-Primes]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Rationals], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, Element[1.3, Rationals], False, Element[a, Rationals], False, False, False}-Rationals]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Reals], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, True, True, Element[a, Reals], False, True, True}-Reals]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Complexes], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, True, True, Element[a, Complexes], False, True, True}-Complexes]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Algebraics], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, Element[1.3, Algebraics], False, Element[a, Algebraics], False, True, False}-Algebraics]
[  167s] FAILED test/builtin/arithmetic/test_element.py::test_element[Table[Element[elem, Booleans], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{False, False, False, False, False, Element[a, Booleans], True, False, False}-Booleans]
[  167s] FAILED test/builtin/calculus/test_limit.py::test_limit[Limit[Tan[x], x->Pi/2]-Indeterminate-None]
[  167s] FAILED test/builtin/calculus/test_limit.py::test_limit[Limit[Cot[x], x->0]-Indeterminate-None]
[  167s] FAILED test/builtin/calculus/test_limit.py::test_limit[Limit[x*Sqrt[2*Pi]^(x^-1)*(Sin[x]/(x!))^(x^-1), x->Infinity]-E-None]
[  167s] FAILED test/builtin/files_io/test_files.py::test_private_doctests_files[DeleteFile[Close[fd]];fd=.;appendFile = OpenAppend["MathicsNonExampleFile"]//{#1[[0]],#1[[1]]}&-None-{OutputStream, MathicsNonExampleFile}-]
[  167s] FAILED test/builtin/files_io/test_files.py::test_private_doctests_files[Close[appendFile]-None-Close[{OutputStream, MathicsNonExampleFile}]-]
[  167s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Elements"]-None-{Data, Grid}-None]
[  167s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Data"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  167s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  167s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "FieldSeparators" -> "."]-None-{{0, 88,0, 60,0, 94}, {0, 76,0, 19,0, 51}, {0, 97,0, 04,0, 26}, {0, 33,0, 74,0, 79}, {0, 42,0, 64,0, 56}}-None]
[  167s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[FileFormat["ExampleData/numberdata.csv"]-None-CSV-None]
[  167s] FAILED test/builtin/numbers/test_trig.py::test_ArcCos - AssertionError
[  167s] FAILED test/builtin/specialfns/test_bessel.py::test_add[z=.;BesselI[1/2,z]-Sqrt[2] Sinh[z] / (Sqrt[z] Sqrt[Pi])-BesselI 1/2 rule]
[  167s] FAILED test/builtin/specialfns/test_bessel.py::test_add[BesselI[-1/2,z]-Sqrt[2] Cosh[z] / (Sqrt[z] Sqrt[Pi])-BesselI -1/2 rule]
[  167s] FAILED test/builtin/specialfns/test_bessel.py::test_add[BesselJ[-1/2,z]-Sqrt[2] Cos[z] / (Sqrt[z] Sqrt[Pi])-BesselJ -1/2 rule]
[  167s] FAILED test/builtin/specialfns/test_bessel.py::test_add[BesselJ[1/2,z]-Sqrt[2] Sin[z] / (Sqrt[z] Sqrt[Pi])-BesselJ 1/2 rule]
[  167s] FAILED test/core/test_streams.py::test_path_search - AssertionError: should f...
[  167s] FAILED test/test_returncode.py::test_returncode - AssertionError: assert 2 == 0
[  167s] = 24 failed, 2950 passed, 287 skipped, 14 xfailed, 16 xpassed, 3 warnings in 151.07s (0:02:31) =
```


[mathics-build.log.gz](https://github.com/user-attachments/files/18669674/mathics-build.log.gz)

**Comment by badshah400** [comment]
The 8.0.1rc1 tarball does not seem to have the operator json tables:

```bash
~> find  ./ -name *.json
./mathics/data/ExampleData/colors.json
```

 so I tried generating them using `./admin-tools/make-JSON-tables.sh`, but that does not work either:

```log
[   12s] + ./admin-tools/make-JSON-tables.sh
[   13s] Usage: mathics3-generate-operator-json-table [OPTIONS] [DATA_DIR]
[   13s] Try 'mathics3-generate-operator-json-table --help' for help.
[   13s]
[   13s] Error: Invalid value for '--output' / '-o': Path '/usr/lib/python3.11/site-packages/mathics_scanner/generate/../data/operators.json' is not writable.
```

No idea what this means, will investigate further tomorrow.

**Comment by rocky** [comment]
> The 8.0.1rc1 tarball does not seem to have the operator json tables:
> 

My fault. Because this didn't go through Python' s setup process. Instead I relied on the mechanism that github uses to dynamically create a tarball from a git tag. 

Here is a tarball create using `python ./setup.py sdist` from the current at the time I wrote this: 

[mathics3-8.0.1.dev0.tar.gz](https://github.com/user-attachments/files/18677999/mathics3-8.0.1.dev0.tar.gz)

> ~> find  ./ -name *.json
> ./mathics/data/ExampleData/colors.json
> so I tried generating them using `./admin-tools/make-JSON-tables.sh`, but that does not work either:
> 
> ```
> [   12s] + ./admin-tools/make-JSON-tables.sh
> [   13s] Usage: mathics3-generate-operator-json-table [OPTIONS] [DATA_DIR]
> [   13s] Try 'mathics3-generate-operator-json-table --help' for help.
> [   13s]
> [   13s] Error: Invalid value for '--output' / '-o': Path '/usr/lib/python3.11/site-packages/mathics_scanner/generate/../data/operators.json' is not writable.
> ```
> 
> No idea what this means, will investigate further tomorrow.

**Comment by badshah400** [comment]
Thanks for spinning me a new tarball. Unfortunately, the same tests are still failing for me. In particular, for test_element.py, I get

```
[   23s] + pushd ./test/builtin/arithmetic
[   23s] ~/test/builtin/arithmetic ~
[   23s] + python3.12 -m pytest ./test_element.py
[   26s] ============================= test session starts ==============================
[   26s] platform linux -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
[   26s] rootdir: /home/abuild/rpmbuild/BUILD/python-Mathics-test-8.0.1_RC1-build/mathics3-8.0.1.dev0
[   26s] configfile: pyproject.toml
[   26s] collected 7 items
[   26s] 
[   26s] test_element.py FFFFFFF                                                  [100%]
[   26s] 
[   26s] =================================== FAILURES ===================================
[   26s] _ test_element[Table[Element[elem, Integers], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]-{True, True, True, False, False, Element[a, Integers], False, False, False}-Integers] _
[   26s] 
[   26s] str_expr = 'Table[Element[elem, Integers], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]'
[   26s] str_expected = '{True, True, True, False, False, Element[a, Integers], False, False, False}'
[   26s] msg = 'Integers'
[   26s] 
[   26s]     @pytest.mark.parametrize(
[   26s]         ("str_expr", "str_expected", "msg"),
[   26s]         [
[   26s]             (
[   26s]                 f"Table[Element[elem, {key}], {test_set}]",
[   26s]                 domains[key],
[   26s]                 key,
[   26s]             )
[   26s]             for key in domains
[   26s]         ],
[   26s]     )
[   26s]     def test_element(str_expr, str_expected, msg):
[   26s] >       check_evaluation(str_expr, str_expected, failure_message=msg)
[   26s] 
[   26s] test_element.py:51: 
[   26s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   26s] 
[   26s] str_expr = 'ToString[Table[Element[elem, Integers], {elem, {1, 2, 4, 1.3, Pi, a, True, Sqrt[5]-2, Sin[3]}}]]'
[   26s] str_expected = 'ToString[{True, True, True, False, False, Element[a, Integers], False, False, False}]'
[   26s] failure_message = 'Integers', hold_expected = False, to_string_expr = True
[   26s] to_string_expected = True, to_python_expected = False, expected_messages = None
[   26s] 
[   26s]     def check_evaluation(
[   26s]         str_expr: Optional[str],
[   26s]         str_expected: Optional[str] = None,
[   26s]         failure_message: Optional[str] = "",
[   26s]         hold_expected: bool = False,
[   26s]         to_string_expr: Optional[bool] = True,
[   26s]         to_string_expected: bool = True,
[   26s]         to_python_expected: bool = False,
[   26s]         expected_messages: Optional[tuple] = None,
[   26s]     ):
[   26s]         """
[   26s]         Helper function to test Mathics expression against
[   26s]         its results.
[   26s]     
[   26s]         Compares the expressions represented by ``str_expr`` and  ``str_expected`` by
[   26s]         evaluating the first, and optionally, the second. If omitted, `str_expected`
[   26s]         is assumed to be `"Null"`.
[   26s]     
[   26s]         str_expr: The expression to be tested. If its value is ``None``, the session is
[   26s]                   reset.
[   26s]                   At the beginning of each set of pytests, it is important to call
[   26s]                   ``check_evaluation(None)`` to avoid that definitions introduced by
[   26s]                   other tests affect the results.
[   26s]     
[   26s]         str_expected: The expected result. The value ``None`` is equivalent to ``"Null"``.
[   26s]     
[   26s]         failure_message: message shown in case of failure. Use "" for no failure message.
[   26s]     
[   26s]         hold_expected:   If ``False`` (default value) the ``str_expected`` is evaluated.
[   26s]                          Otherwise, the expression is considered literally.
[   26s]     
[   26s]         to_string_expr: If ``True`` (default value) the result of the evaluation is
[   26s]                         converted into a Python string. Otherwise, the expression is kept
[   26s]                         as an Expression object.
[   26s]                         If this argument is set to ``None``, the session is reset.
[   26s]     
[   26s]         to_string_expected: If ``True`` (default value) the expected expression is
[   26s]                             evaluated and then converted to a Python string. result of the
[   26s]                             evaluation is converted into a Python string.
[   26s]                             If ``False``, the expected expression is kept as an Expression
[   26s]                             object.
[   26s]                             If ``None`` the result string is matched as is.
[   26s]     
[   26s]         to_python_expected: If ``True``, and ``to_string_expected`` is ``False``, the result
[   26s]                             of evaluating ``str_expr``is compared against the result of the
[   26s]                             evaluation of ``str_expected``, converted into a
[   26s]                             Python object.
[   26s]     
[   26s]         expected_messages: If a tuple of strings are passed into
[   26s]                            this parameter, messages and prints raised during
[   26s]                            the evaluation of ``str_expr`` are compared with the elements of
[   26s]                            the list. If ``None``, this comparison
[   26s]                            is omitted.
[   26s]         """
[   26s]         if str_expr is None:
[   26s]             reset_session()
[   26s]             return
[   26s]         if str_expected is None:
[   26s]             str_expected = "Null"
[   26s]     
[   26s]         if to_string_expr:
[   26s]             str_expr = f"ToString[{str_expr}]"
[   26s]             result = evaluate_value(str_expr)
[   26s]         elif to_string_expr is None:
[   26s]             result = str_expr
[   26s]         else:
[   26s]             result = evaluate(str_expr)
[   26s]     
[   26s]         outs = [out.text for out in session.evaluation.out]
[   26s]     
[   26s]         if to_string_expected:
[   26s]             if hold_expected:
[   26s]                 expected = str_expected
[   26s]             else:
[   26s]                 str_expected = f"ToString[{str_expected}]"
[   26s]                 expected = evaluate_value(str_expected)
[   26s]         elif to_string_expected is None:
[   26s]             expected = str_expected
[   26s]         else:
[   26s]             if hold_expected:
[   26s]                 if to_python_expected:
[   26s]                     expected = str_expected
[   26s]                 else:
[   26s]                     expected = evaluate(f"HoldForm[{str_expected}]").elements[0]
[   26s]             else:
[   26s]                 expected = evaluate(str_expected)
[   26s]                 if to_python_expected:
[   26s]                     expected = expected.to_python(string_quotes=False)
[   26s]     
[   26s]         print(time.asctime())
[   26s]         if failure_message:
[   26s]             print((result, expected))
[   26s] >           assert result == expected, failure_message
[   26s] E           AssertionError: Integers
[   26s] 
[   26s] ../../helper.py:130: AssertionError

```

and on and on. Build log [here](https://github.com/user-attachments/files/18683355/mathics-build.log),

**Comment by rocky** [comment]
I will try to recreate this problem in my virtual environment later.   I am really puzzled by this behavior since there is no unicode involved as far as I can tell. 

When you run `mathics`  and type `Element == [Pi,  Integers]`  and `Element[1, Integers]` what do you get? 

Here is what I see: 

```
$ mathics

Mathics3 8.0.1.dev0
on CPython 3.12.8 (main, Jan  2 2025, 12:55:52) [GCC 14.2.0]
using SymPy 1.13.3, mpmath 1.3.0, numpy 1.26.4, cython Not installed
...
In[1]:= Element[Pi, Integers]
Out[1]= False

In[2]:= Element[1, Integers]
Out[2]= True

```

If you get the same thing, then the code works, but the test is somehow failing. 

How can I try the 8.0.1dev0 RPM you built? 

The only other thing I can think of (but it doesn't make any sense is the `LANG` environment setting. I have `en_US.UTF-8` and I tried setting this to `C` and both of these worked.

**Comment by badshah400** [comment]
> When you run `mathics` and type `Element == [Pi, Integers]` and `Element[1, Integers]` what do you get?
> 
> Here is what I see:
> 
> ```
> $ mathics
> 
> Mathics3 8.0.1.dev0
> on CPython 3.12.8 (main, Jan  2 2025, 12:55:52) [GCC 14.2.0]
> using SymPy 1.13.3, mpmath 1.3.0, numpy 1.26.4, cython Not installed
> ...
> In[1]:= Element[Pi, Integers]
> Out[1]= False
> 
> In[2]:= Element[1, Integers]
> Out[2]= True
> ```
> 
> If you get the same thing, then the code works, but the test is somehow failing.

Nope, it does not seem to evaluate at all; I see the following:

```plain
Mathics3 8.0.1.dev0
on CPython 3.11.11 (main, Dec 04 2024, 21:44:34) [GCC]
using SymPy 1.13.3, mpmath 1.3.0, numpy 1.26.4, cython 3.0.11

Copyright (C) 2011-2025 The Mathics3 Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by evaluating Quit[] or by pressing CONTROL-D.

In[1]:= Element[Pi, Integers]
Out[1]= Element[Pi, Integers]

In[2]:= Element[1, Integers]
Out[2]= Element[1, Integers]

In[3]:= Element[Pi, Integers]
Out[3]= Element[Pi, Integers]

```

So, there seems to be a real issue with my rpms, not limited to tests alone.

> 
> How can I try the 8.0.1dev0 RPM you built?
> 

Now available from the same website: https://download.opensuse.org/repositories/home:/badshah400:/branches:/science/openSUSE_Tumbleweed/noarch/

> The only other thing I can think of (but it doesn't make any sense is the `LANG` environment setting. I have `en_US.UTF-8` and I tried setting this to `C` and both of these worked.

Tried both, neither worked.

**Comment by mmatera** [comment]
It looks like the `autoload` modules are not loaded.

**Comment by rocky** [comment]
As before @mmatera had the key insight as to what's wrong.  I was not packaging some needed Mathics3 Rules in the tarball (or wheel).  I've just corrected this and a new tarball is attached which now includes the missing files. 

[mathics3-8.0.1.dev0.tar.gz](https://github.com/user-attachments/files/18693346/mathics3-8.0.1.dev0.tar.gz)

@badshah400 I would be grateful if you would try the attached tarball to see if this fixes the problem. If so, it will appear in a new release probably over the weekened.

**Comment by badshah400** [comment]
Big thanks, this helped almost get a fully successful build. In particular, `test_element`, `test_limit`, `test_ArcCos`, and `test_bessel.py::test_add` all pass now. However the following tests still fail:

```
[  173s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Elements"]-None-{Data, Grid}-None]
[  173s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Data"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  173s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  173s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "FieldSeparators" -> "."]-None-{{0, 88,0, 60,0, 94}, {0, 76,0, 19,0, 51}, {0, 97,0, 04,0, 26}, {0, 33,0, 74,0, 79}, {0, 42,0, 64,0, 56}}-None]
[  173s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[FileFormat["ExampleData/numberdata.csv"]-None-CSV-None]
[  173s] FAILED test/core/test_streams.py::test_path_search - AssertionError: should f...
[  173s] FAILED test/test_returncode.py::test_returncode - AssertionError: assert 2 == 0
[  173s] = 7 failed, 2966 passed, 287 skipped, 14 xfailed, 16 xpassed, 3 warnings in 149.21s (0:02:29) =
```

We're down to 7 stubborn so and so's 😉

Full build log [here](https://github.com/user-attachments/files/18694000/mathics-build.log).

**Comment by mmatera** [comment]
Looks like `ExampleData` was not packed either.

**Comment by badshah400** [comment]
> Looks like `ExampleData` was not packed either.

Here is what I have in the RPM:

```bash
~> rpm -qvlp ./binaries/python311-Mathics-8.0.1~RC1-0.noarch.rpm | grep "ExampleData"
drwxr-xr-x    2 root     root                        0 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData
-rw-r--r--    1 root     root                     3858 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/BloodToilTearsSweat.txt
-rw-r--r--    1 root     root                    53455 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/Einstein.jpg
-rw-r--r--    1 root     root                     3175 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/EinsteinSzilLetter.txt
-rw-r--r--    1 root     root                      217 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/ExampleData.txt
-rw-r--r--    1 root     root                   196929 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/InventionNo1.xml
-rw-r--r--    1 root     root                    26866 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/MadTeaParty.gif
-rw-r--r--    1 root     root                    16631 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/Middlemarch.txt
-rw-r--r--    1 root     root                      303 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/Namespaces.xml
-rw-r--r--    1 root     root                   175608 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/PrimeMeridian.html
-rw-r--r--    1 root     root                    11126 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/Testosterone.svg
-rw-r--r--    1 root     root                     9891 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/TextRecognize.png
-rw-r--r--    1 root     root                      599 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/benzene.xyz
-rw-r--r--    1 root     root                       26 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/bignum.txt
-rw-r--r--    1 root     root                     1035 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/colors.json
-rw-r--r--    1 root     root                     2739 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/copyright.csv
-rw-r--r--    1 root     root                  1551537 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/hedy.tif
-rw-r--r--    1 root     root                       19 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/language.txt
-rw-r--r--    1 root     root                    65849 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/moon.tif
-rw-r--r--    1 root     root                       80 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/numberdata.csv
-rw-r--r--    1 root     root                       30 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/numbers.txt
-rw-r--r--    1 root     root                       43 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/sentences.txt
-rw-r--r--    1 root     root                       29 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/strings.txt
-rw-r--r--    1 root     root                   142286 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/sunflowers.jpg
-rw-r--r--    1 root     root                       31 Feb  6 22:56 /usr/lib/python3.11/site-packages/mathics/data/ExampleData/words.txt

```

**Comment by rocky** [comment]
I am seeing that we are misclassifying "ExampleData/numberdata.csv" as a "Binary" file instead of a "CSV" file. 

```
In[1]:= FileFormat["ExampleData/numberdata.csv"]
Out[1]= "Binary"
```
Why? I don't know yet. It may be other files are being categorized as Binary as well instead of whatever corresponding type they should be.  

Hopefully, we will have a fix soon.

**Comment by badshah400** [comment]
[This file](../blob/master/test/data/recursive-gcd.wl) also seems to be missing, and I see references to it in the `pytest` failures:

```
[  173s] mathics: error: argument FILE: can't open '/home/abuild/rpmbuild/BUILD/python-Mathics-test-8.0.1_RC1-build/mathics3-8.0.1.dev0/test/data/recursive-gcd.wl': [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/python-Mathics-test-8.0.1_RC1-build/mathics3-8.0.1.dev0/test/data/recursive-gcd.wl'
```

Copying this file manually to the `test/data/` dir fixes the `test_streams.py::test_path_search` and `test_returncode.py::test_returncode`, it looks like we are left with just the `csv` import issue:

```log
[  182s] =========================== short test summary info ============================
[  182s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Elements"]-None-{Data, Grid}-None]
[  182s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "Data"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  182s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv"]-None-{{0.88, 0.60, 0.94}, {0.76, 0.19, 0.51}, {0.97, 0.04, 0.26}, {0.33, 0.74, 0.79}, {0.42, 0.64, 0.56}}-None]
[  182s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[Import["ExampleData/numberdata.csv", "FieldSeparators" -> "."]-None-{{0, 88,0, 60,0, 94}, {0, 76,0, 19,0, 51}, {0, 97,0, 04,0, 26}, {0, 33,0, 74,0, 79}, {0, 42,0, 64,0, 56}}-None]
[  182s] FAILED test/builtin/files_io/test_importexport.py::test_private_doctests_importexport[FileFormat["ExampleData/numberdata.csv"]-None-CSV-None]
[  182s] = 5 failed, 2968 passed, 287 skipped, 14 xfailed, 16 xpassed, 3 warnings in 158.66s (0:02:38) =
```

Outside of the test, on my system, importing `csv` fails too:

```
~> mathics

Mathics3 8.0.1.dev0
on CPython 3.11.11 (main, Dec 04 2024, 21:44:34) [GCC]
using SymPy 1.13.3, mpmath 1.3.0, numpy 1.26.4, cython 3.0.11

Copyright (C) 2011-2025 The Mathics3 Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by evaluating Quit[] or by pressing CONTROL-D.

In[1]:= Import[$InstallationDirectory <> "/data/ExampleData/numberdata.csv"]
Import::fmtnosup: Binary is not a supported Import format.
Out[1]= $Failed
```

**Comment by rocky** [comment]
It looks like the mime type of numberdata.csv is getting tagged as "text/x-comma-separated-values" which we don't detect as CSV. (We had only "text/comma-separated-values".

In the attached tarball, I've added this mime type and added `test/data/recursive-gcd.wl`

[mathics3-8.0.1.dev0.tar.gz](https://github.com/user-attachments/files/18698565/mathics3-8.0.1.dev0.tar.gz)

Hopefully, this will address the remaining testing problems.

**Comment by badshah400** [comment]
> It looks like the mime type of numberdata.csv is getting tagged as "text/x-comma-separated-values" which we don't detect as CSV. (We had only "text/comma-separated-values".
> 
> In the attached tarball, I've added this mime type and added `test/data/recursive-gcd.wl`
> 
> [mathics3-8.0.1.dev0.tar.gz](https://github.com/user-attachments/files/18698565/mathics3-8.0.1.dev0.tar.gz)
> 
> Hopefully, this will address the remaining testing problems.

Yes, all green now.

@rocky @mmatera 
Thanks a lot, for all the work in fixing these issues. Having a fully successful `pytest` without any `-k 'not FOO'` delights me no end.

**Comment by mmatera** [comment]
@badshah400 you are welcome, and thank you very much for working on this!

**Comment by rocky** [comment]
@badshah400 Thanks for seeing this through.  

For my part, I realize I need to test the wheels and tarball better before a release. I will add this to my release process notes. 

FYI from a openSUSE's users perspective though, this package is just what the kernel. It has a minimal command-line interface. 

For a better comnand-line,  mathicsscript is better since it has command-completion, better Unicode integration and handles showing graphics via matplotlib or asymptote.  

And for a more GUI interface there is mathics-django. In the future, we may have integration with jupyter worked out better, but for now this is the best for viewing the documentation along with a interactive (primitive) notebook setting that has graphics integrated into it. 

And finally, there is the documentation.  I will be bundling a PDF inside the wheel, since building this from scratch is very involved and needs texlive-xtex, tetexlive-latexmk-bin, texlife-epstopdf-bin, texlive-pdftex, asymptote, and inkscape, 

 The last published doc is https://mathics.org/docs/mathics-latest.pdf

**Comment by badshah400** [comment]
> For a better comnand-line, mathicsscript is better since it has command-completion, better Unicode integration and handles showing graphics via matplotlib or asymptote.

We also package this already as well as mathics-pygments (I actively update both):

* https://build.opensuse.org/package/show/openSUSE:Factory/python-Mathics-Scanner (update to 1.4.1 [submitted](https://build.opensuse.org/requests/1243885) already)
* https://build.opensuse.org/package/show/openSUSE:Factory/python-mathics-pygments

> And for a more GUI interface there is mathics-django

Working on this, hopefully by the weekend along with the new Mathics version.

> And finally, there is the documentation. I will be bundling a PDF inside the wheel and tarball, since building this from scratch is very involved and needs texlive-xtex, tetexlive-latexmk-bin, texlife-epstopdf-bin, texlive-pdftex, asymptote, and inkscape,

Yes, indeed that would be great! I can include that in the package as a doc item.

If there is anything additional related to Mathics we could package, please let me know.

**Comment by badshah400** [comment]
Oops, sorry, meant to point to `python-mathicsscript` not `scanner`. The former is being updated to 8.0.0:

* https://build.opensuse.org/package/show/home:badshah400:branches:science/python-mathicsscript

**Comment by rocky** [comment]
> If there is anything additional related to Mathics we could package, please let me know.

The other two packages that we regularly update are the [Mathics3 module for Networks and Graphs 
](https://github.com/Mathics3/pymathics-graph) and the [Mathics3 module for that hooks in to NLP
](https://github.com/Mathics3/pymathics-language).

Over the next year, things may change drastically; but for now I'd say this is it.

**Comment by badshah400** [comment]
We have all tests succeeding on openSUSE now, so I'll take the liberty of closing this issue. Thanks for all the help.
